### ISSUE TITLE
CivilSurface not working correctly

### ISSUE THREAD

**Issue by RedRai123** [Autodesk/civilconnection#12] opened 2019-10-10 06:01 UTC
Hi Paolo,

I have tried the new CivilSurface Nodes in your package, but it doesnt work unfortunately.
So Im able to get the CivilSurface, but as soon as I want to get the Surfaces from a small DTM with the "CivilSurface.GetTrianglesSurfaces" Node, my Dynamo is loading and nothing happens anymore. (for more than 1 hour).
When Im using the second node "CivilSurface.GetTrianglesSurfaces" with XML Path, my Dynamo is crashing.
Any idea what could be wrong?

**Comment by paoloemilioserra** [comment] 2019-10-10 07:02
Hi @RedRai123 did you install the latest version of CivilPython as well?

**Comment by RedRai123** [comment] 2019-10-10 10:30
Yes I did, but doesnt help :(

**Comment by RedRai123** [comment] 2019-10-10 10:32
![2019-10-10 12_30_58-Dynamo](https://user-images.githubusercontent.com/42736086/66561521-eea63f00-eb59-11e9-8372-3656bf72519e.png)

Or the outcome is only "Null"

**Comment by paoloemilioserra** [comment] 2019-10-10 13:00
That's fine @RedRai123, then you need to export the LandXML manually from Civil 3D selecting only the surface and pass the XML path

**Comment by paoloemilioserra** [comment] 2019-10-10 13:28
Just for reference, in your Temp folder there is a CivilConnection_temp.log file every time you run a Dynamo graph that contains a CivilConnection node. It helps a ton if you share also the content of that file as it might capture errors and steps that are useful for debugging.

**Comment by paoloemilioserra** [comment] 2019-10-11 23:57
So for your reference I managed to create a Surface of more than 25000 triangles and create a single PolySurface using the LandXML. I'm closing this.

**Closed as completed by paoloemilioserra** 2019-10-11 23:57 UTC

**Comment by RedRai123** [comment] 2019-12-02 13:21
Sorry to come back to this topic, but my colleagues and me are still facing the same problem. I checked the log file and it just cant procceed:

ERROR: Unable to create polygon : API_FAILED -- operation unsuccessful
ERROR: Unable to create polygon : UNEXPECTED_EXCEPTION -- Unexpected system exception

Could you take a look at the log file? 

Thanks in advance!
[CivilConnection_temp.log](https://github.com/Autodesk/civilconnection/files/3911429/CivilConnection_temp.log)

**Comment by paoloemilioserra** [comment] 2019-12-02 13:27
@RedRai123 unfortunately in this case the error doesn't help much I'll need the dataset as well to reproduce it. I'd suggest you look for an alternative workflow in the meantime because realistically I don't have time to work on this project until February.
